name: Canary

# This workflow creates or updates (if already exists) a pull request with new
# version bump on every commit to main.

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**/*.ts'
      - 'packages/**/*.tsx'
      - 'www/src/**/'
      - '!lerna.json'

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: main
          fetch-depth: 0

      - name: Install dependencies
        run: |
          yarn install

      - name: Build packages
        run: |
          yarn build

      - name: Create canary release
        run: |
          yarn lerna version prerelease --conventional-commits --no-git-tag-version --no-push --preid canary --yes --exact
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore: Publish"

      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM registry with canary tag
        run: yarn lerna publish from-package --yes --dist-tag canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: git reset --hard

      - name: Build documentation
        run: |
          yarn website-canary

      - name: Deploy canary documentation
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: docs # The branch the action should deploy to.
          CLEAN: false # Don't remove deleted files from the deploy branch
          FOLDER: docs # The folder the action should deploy.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SINGLE_COMMIT: true
